### ISSUE TITLE
Wifi reconnect

### ISSUE THREAD

**Issue by SaschaHeymann** [doublerobotics/d3-sdk#2]
We have a WIFI Mash with several WIFI APs in our production hall. Currently our WIFI infrastructure is faulty which leads to connection failures. Of course the connection failures are our "issue". 
However, there is an Issue with D3 which can not reconnect to the configured WIFI after a disconnection.

### Procedure:
WIFI connection termination (failure on infrastructure side) -> WIFI selection window at D3
Problem -> reconnect requires WIFI password input on D3 -> D3 service restarts-> connection not possible, prompt again for WIFI selction and password.
**Expected behaviour:** Connection termination of WIFI_1-> wait until WIFI_1 is available again or change to another stored WIFI_2 profile.

**Comment by davidcann** [comment]
We'll try to reproduce this. It should try to reconnect automatically and it shouldn't restart at all during that process. Do you know if the WiFi access points are turning off (as in, the network disappearing) or if the local WiFi network is still up, but the connection to the internet is going offline? The system checks for both.

**Comment by doublerobotics** [comment]
Release 1.0.26 includes improvements to WiFi re-connection. The next update will include additional changes to better communicate to the user what is happening.
