### ISSUE TITLE
navigate.drive is unable to perform smooth drive

### ISSUE THREAD

**Issue by gimdh** [doublerobotics/d3-sdk#8]
I cannot get smooth drive even if I continuously repeat following command using Unix socket. It seems it still stops for every 500ms or so. Am I missing something?

```
{
    "c": "navigate.drive",
    "d": { "throttle": 1, "turn": 0, "powerDrive": True}
}
```

**Comment by davidcann** [comment]
Does it work correctly when driving from the Developer Monitor web page? You can either click and hold on the up arrow button or enable keyboard driving and hold the up arrow key. Those use the same exact command sent to the API.

Note that you can see all commands going through the API in the API tab's log section.

**Comment by gimdh** [comment]
Oh, apparently 200ms delay was mandatory. Closing the issue.
